### Objective : 
To understand customer's preference for food items and quantity of items to be ordered. The information is helpful for the shop owner to decide the stock for raw materials
##### Reference : https://nitarane.wordpress.com/

#### Chipotle Dataset from : https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv 

### Strutures of data
order_id, quantity, item_name, choice_description, item_price

In [2]:
import pandas as pd
import numpy as np

In [3]:
location = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv",sep="\t")
location.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [4]:
location.shape

(4622, 5)

In [5]:
location.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

# Memory usage tells an approximate amount of RAM used to hold the DataFrame which can to write more efficient code. 
It avoids accidental copies of data which caused the slowness.

In [6]:
location.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [7]:
# item_price is supposed to be in float but not object 
# Thus, use lambda function to convert it to float 
# And apply() to the record

ip = lambda x: float(x[1:-1])
location.item_price = location.item_price.apply(ip)

In [8]:
location.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [9]:
location.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [10]:
location.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

In [11]:
def get_var_category(series): 
    unique_count = series.nunique(dropna= False)
    total_count = len(series)
    if pd.api.types.is_numeric_dtype(series):
        return 'Numerical'
    elif pd.api.types.is_datetime64_dtype(series):
        return 'Date'
    elif unique_count == total_count:
        return 'Text(Unique)'
    else: 
        return 'Categorical'
    
def print_categories(df):
    for column_name in df.columns:
        print(column_name,": ", get_var_category(df[column_name]))

In [12]:
print_categories(location)

order_id :  Numerical
quantity :  Numerical
item_name :  Categorical
choice_description :  Categorical
item_price :  Numerical

In [13]:
# Calculate number of missing values in Length and Count

number_of_missing_values = 4622 - 3376 
pct_of_missing_values = float(number_of_missing_values/4622)
pct_of_missing_values = "{0:.1f}%".format(pct_of_missing_values*100)
print(pct_of_missing_values)

27.0%

In [14]:
print('Display Column : \n'+str(location['item_name']))

Display Column :
0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
5                                Chicken Bowl
6                               Side of Chips
7                               Steak Burrito
8                            Steak Soft Tacos
9                               Steak Burrito
10                        Chips and Guacamole
11                       Chicken Crispy Tacos
12                         Chicken Soft Tacos
13                               Chicken Bowl
14                        Chips and Guacamole
15      Chips and Tomatillo-Green Chili Salsa
16                            Chicken Burrito
17                            Chicken Burrito
18                                Canned Soda
19                               Chicken Bowl
20                        Chips and Guacamole
21                           Barbacoa Burrito
22                           Nantucket Nectar
23                            Chicken Burrito
24                                       Izze
25               Chips and Fresh Tomato Salsa
26                               Chicken Bowl
27                           Carnitas Burrito
28                                Canned Soda
29                            Chicken Burrito
                        ...
4592                         Barbacoa Burrito
4593                            Carnitas Bowl
4594                            Barbacoa Bowl
4595                             Chicken Bowl
4596                      Chips and Guacamole
4597                        Canned Soft Drink
4598                            Bottled Water
4599                             Chicken Bowl
4600                      Chips and Guacamole
4601                        Canned Soft Drink
4602                         Barbacoa Burrito
4603                         Barbacoa Burrito
4604                             Chicken Bowl
4605                      Chips and Guacamole
4606                        Canned Soft Drink
4607                            Steak Burrito
4608                           Veggie Burrito
4609                        Canned Soft Drink
4610                            Steak Burrito
4611                           Veggie Burrito
4612                            Carnitas Bowl
4613                                    Chips
4614                            Bottled Water
4615                       Chicken Soft Tacos
4616                      Chips and Guacamole
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: object

In [15]:
print('Display any combination of Columns: \n'+str(location[['item_name','choice_description']]))

Display any combination of Columns:
                                  item_name  \
0              Chips and Fresh Tomato Salsa
1                                      Izze
2                          Nantucket Nectar
3     Chips and Tomatillo-Green Chili Salsa
4                              Chicken Bowl
5                              Chicken Bowl
6                             Side of Chips
7                             Steak Burrito
8                          Steak Soft Tacos
9                             Steak Burrito
10                      Chips and Guacamole
11                     Chicken Crispy Tacos
12                       Chicken Soft Tacos
13                             Chicken Bowl
14                      Chips and Guacamole
15    Chips and Tomatillo-Green Chili Salsa
16                          Chicken Burrito
17                          Chicken Burrito
18                              Canned Soda
19                             Chicken Bowl
20                      Chips and Guacamole
21                         Barbacoa Burrito
22                         Nantucket Nectar
23                          Chicken Burrito
24                                     Izze
25             Chips and Fresh Tomato Salsa
26                             Chicken Bowl
27                         Carnitas Burrito
28                              Canned Soda
29                          Chicken Burrito
...                                     ...
4592                       Barbacoa Burrito
4593                          Carnitas Bowl
4594                          Barbacoa Bowl
4595                           Chicken Bowl
4596                    Chips and Guacamole
4597                      Canned Soft Drink
4598                          Bottled Water
4599                           Chicken Bowl
4600                    Chips and Guacamole
4601                      Canned Soft Drink
4602                       Barbacoa Burrito
4603                       Barbacoa Burrito
4604                           Chicken Bowl
4605                    Chips and Guacamole
4606                      Canned Soft Drink
4607                          Steak Burrito
4608                         Veggie Burrito
4609                      Canned Soft Drink
4610                          Steak Burrito
4611                         Veggie Burrito
4612                          Carnitas Bowl
4613                                  Chips
4614                          Bottled Water
4615                     Chicken Soft Tacos
4616                    Chips and Guacamole
4617                          Steak Burrito
4618                          Steak Burrito
4619                     Chicken Salad Bowl
4620                     Chicken Salad Bowl
4621                     Chicken Salad Bowl

                                     choice_description
0                                                   NaN
1                                          [Clementine]
2                                               [Apple]
3                                                   NaN
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...
6                                                   NaN
7     [Tomatillo Red Chili Salsa, [Fajita Vegetables...
8     [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...
9     [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...
10                                                  NaN
11    [Roasted Chili Corn Salsa, [Fajita Vegetables,...
12    [Roasted Chili Corn Salsa, [Rice, Black Beans,...
13    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...
14                                                  NaN
15                                                  NaN
16    [Tomatillo-Green Chili Salsa (Medium), [Pinto ...
17    [Fresh Tomato Salsa (Mild), [Black Beans, Rice...
18                                             [Sprite]
19    [Tomatillo Red Chili Salsa, [Fajita Vegetables...
20                                                  NaN
21    [[Fresh Tomato Salsa (Mild), Tomatillo-Green C...
22                                 [Pomegranate Cherry]
23    [[Tomatillo-Green Chili Salsa (Medium), Tomati...
24                                         [Grapefruit]
25                                                  NaN
26    [Roasted Chili Corn Salsa (Medium), [Pinto Bea...
27    [[Tomatillo-Green Chili Salsa (Medium), Roaste...
28                                         [Dr. Pepper]
29    [Tomatillo-Green Chili Salsa (Medium), [Pinto ...
...                                                 ...
4592  [Tomatillo Red Chili Salsa, [Rice, Fajita Vege...
4593  [Roasted Chili Corn Salsa, [Rice, Sour Cream, ...
4594  [Roasted Chili Corn Salsa, [Pinto Beans, Sour ...
4595  [Tomatillo Green Chili Salsa, [Rice, Black Bea...
4596                                                NaN
4597                                           [Nestea]
4598                                                NaN
4599      [Roasted Chili Corn Salsa, [Cheese, Lettuce]]
4600                                                NaN
4601                                        [Diet Coke]
4602                      [Tomatillo Green Chili Salsa]
4603                      [Tomatillo Green Chili Salsa]
4604  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...
4605                                                NaN
4606                                             [Coke]
4607  [Tomatillo Green Chili Salsa, [Rice, Cheese, S...
4608  [Tomatillo Red Chili Salsa, [Fajita Vegetables...
4609                                           [Sprite]
4610  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...
4611  [Tomatillo Green Chili Salsa, [Rice, Fajita Ve...
4612  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...
4613                                                NaN
4614                                                NaN
4615   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]
4616                                                NaN
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...

[4622 rows x 2 columns]

In [16]:
# Display only 2 columns in DataFrame 
lef = location.loc[:, ['item_name','item_price']]
lef

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito        8.49
17                          Chicken Burrito        8.49
18                              Canned Soda        2.18
19                             Chicken Bowl        8.75
20                      Chips and Guacamole        4.45
21                         Barbacoa Burrito        8.99
22                         Nantucket Nectar        3.39
23                          Chicken Burrito       10.98
24                                     Izze        3.39
25             Chips and Fresh Tomato Salsa        2.39
26                             Chicken Bowl        8.49
27                         Carnitas Burrito        8.99
28                              Canned Soda        1.09
29                          Chicken Burrito        8.49
...                                     ...         ...
4592                       Barbacoa Burrito       11.75
4593                          Carnitas Bowl       11.75
4594                          Barbacoa Bowl       11.75
4595                           Chicken Bowl        8.75
4596                    Chips and Guacamole        4.45
4597                      Canned Soft Drink        1.25
4598                          Bottled Water        1.50
4599                           Chicken Bowl        8.75
4600                    Chips and Guacamole        4.45
4601                      Canned Soft Drink        1.25
4602                       Barbacoa Burrito        9.25
4603                       Barbacoa Burrito        9.25
4604                           Chicken Bowl        8.75
4605                    Chips and Guacamole        4.45
4606                      Canned Soft Drink        1.25
4607                          Steak Burrito       11.75
4608                         Veggie Burrito       11.25
4609                      Canned Soft Drink        1.25
4610                          Steak Burrito       11.75
4611                         Veggie Burrito       11.25
4612                          Carnitas Bowl        9.25
4613                                  Chips        2.15
4614                          Bottled Water        1.50
4615                     Chicken Soft Tacos        8.75
4616                    Chips and Guacamole        4.45
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [17]:
print('Display any row from Datasset by mentioning the position/row number : \n' + str(location.iloc[34]))

Display any row from Datasset by mentioning the position/row number :
order_id                         17
quantity                          1
item_name             Bottled Water
choice_description              NaN
item_price                     1.09
Name: 34, dtype: object

In [18]:
print('Display any row from the Dataset by mentioning the index : \n'+ str(location.loc[34]))

Display any row from the Dataset by mentioning the index :
order_id                         17
quantity                          1
item_name             Bottled Water
choice_description              NaN
item_price                     1.09
Name: 34, dtype: object

#### Apply Filter, Sort or Group By to analyse data to find out customer's preference

In [19]:
print('Most ordered item in choice_description: \n' + str(location.choice_description.value_counts().head()) )

Most ordered item in choice_description:
[Diet Coke]                                                                          134
[Coke]                                                                               123
[Sprite]                                                                              77
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Lettuce]]                42
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]     40
Name: choice_description, dtype: int64

In [20]:
print('Most ordered item in item_name column: \n' + str(location.item_name.value_counts().head()))

Most ordered item in item_name column:
Chicken Bowl           726
Chicken Burrito        553
Chips and Guacamole    479
Steak Burrito          368
Canned Soft Drink      301
Name: item_name, dtype: int64

In [21]:
# value_counts function returns object containing counts of unique values
location.quantity.value_counts(dropna=False)

1     4355
2      224
3       28
4       10
15       1
7        1
10       1
5        1
8        1
Name: quantity, dtype: int64

The result indicates majority of items are ordered only once. There is just 1 item ordered whose quantity is 15 (max quantity)
This helps the owner to know the frequency of various items ordered.

In [22]:
print('Total items ordered :\n' + str(location.quantity.sum()))

Total items ordered :
4972

In [23]:
print('TYPE 1 \n Total number of orders : ' + str(location.order_id.value_counts().count() ) + '\n')

TYPE 1
 Total number of orders : 1834

In [24]:
print ('Total revenue generated : \n' + str(location.item_price.sum()))

Total revenue generated :
34500.16

In [25]:
print('TYPE 1 \n Number of different items sold: ' + str(len(location.item_name.unique())) + '\n')

print('TYPE 2 \n Number of different items sold: ' + str(location.item_name.value_counts().count()))

TYPE 1
 Number of different items sold: 50

TYPE 2
 Number of different items sold: 50

In [26]:
# Make the comparison 
chipo10 = location[location['item_price']>10.00]
chipo10.head()

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98

In [27]:
len(chipo10)

1130

In [28]:
# AS : Average Cost or Average Price? 
avg_order = location.item_price.sum()/location.order_id.value_counts().count()

print ("The average cost per order is: $%s" % round(avg_order, 2))

The average cost per order is: $18.81

In [29]:
# Slicing the dataset column-wise 
# To get the item and its price

# Delete the duplicates in item_name and quantity 
chipo_filtered = location.drop_duplicates(['item_name','quantity'])

# select only the ones with quantity equals to 1 
price_per_item = chipo_filtered[chipo_filtered.quantity == 1]

price_per_item = price_per_item[['item_name','item_price']]

# sort the values from the most to less expensive 
price_per_item.sort_values(by = "item_price", ascending = False)

                                  item_name  item_price
606                        Steak Salad Bowl       11.89
1229                    Barbacoa Salad Bowl       11.89
1132                    Carnitas Salad Bowl       11.89
7                             Steak Burrito       11.75
168                   Barbacoa Crispy Tacos       11.75
39                            Barbacoa Bowl       11.75
738                       Veggie Soft Tacos       11.25
186                       Veggie Salad Bowl       11.25
62                              Veggie Bowl       11.25
57                           Veggie Burrito       11.25
250                           Chicken Salad       10.98
5                              Chicken Bowl       10.98
8                          Steak Soft Tacos        9.25
554                   Carnitas Crispy Tacos        9.25
237                     Carnitas Soft Tacos        9.25
56                      Barbacoa Soft Tacos        9.25
92                       Steak Crispy Tacos        9.25
664                             Steak Salad        8.99
54                               Steak Bowl        8.99
3750                         Carnitas Salad        8.99
21                         Barbacoa Burrito        8.99
27                         Carnitas Burrito        8.99
33                            Carnitas Bowl        8.99
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
44                       Chicken Salad Bowl        8.75
1653                    Veggie Crispy Tacos        8.49
16                          Chicken Burrito        8.49
1694                           Veggie Salad        8.49
1414                                  Salad        7.40
510                                 Burrito        7.40
520                            Crispy Tacos        7.40
673                                    Bowl        7.40
298                       6 Pack Soft Drink        6.49
10                      Chips and Guacamole        4.45
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
674       Chips and Mild Fresh Tomato Salsa        3.00
111     Chips and Tomatillo Red Chili Salsa        2.95
233      Chips and Roasted Chili Corn Salsa        2.95
38    Chips and Tomatillo Green Chili Salsa        2.95
3     Chips and Tomatillo-Green Chili Salsa        2.39
300     Chips and Tomatillo-Red Chili Salsa        2.39
191      Chips and Roasted Chili-Corn Salsa        2.39
0              Chips and Fresh Tomato Salsa        2.39
40                                    Chips        2.15
6                             Side of Chips        1.69
263                       Canned Soft Drink        1.25
28                              Canned Soda        1.09
34                            Bottled Water        1.09

In [30]:
print ("Number of times people ordered more than one canned soda " )
# It can be any item 
chipo_ml = location[(location.item_name == "Canned Soda") & (location.quantity >1)]
chipo_ml

Number of times people ordered more than one canned soda

      order_id  quantity    item_name choice_description  item_price
18           9         2  Canned Soda           [Sprite]        2.18
51          23         2  Canned Soda     [Mountain Dew]        2.18
162         73         2  Canned Soda        [Diet Coke]        2.18
171         76         2  Canned Soda  [Diet Dr. Pepper]        2.18
350        150         2  Canned Soda        [Diet Coke]        2.18
352        151         2  Canned Soda        [Coca Cola]        2.18
698        287         2  Canned Soda        [Coca Cola]        2.18
700        288         2  Canned Soda        [Coca Cola]        2.18
909        376         2  Canned Soda     [Mountain Dew]        2.18
1091       450         2  Canned Soda       [Dr. Pepper]        2.18
1092       450         2  Canned Soda        [Coca Cola]        2.18
1944       787         2  Canned Soda       [Dr. Pepper]        2.18
2135       859         2  Canned Soda        [Diet Coke]        2.18
2235       901         4  Canned Soda           [Sprite]        4.36
2905      1156         2  Canned Soda        [Coca Cola]        2.18
2906      1156         2  Canned Soda           [Sprite]        2.18
3152      1258         2  Canned Soda       [Dr. Pepper]        2.18
3364      1349         2  Canned Soda        [Coca Cola]        2.18
3592      1440         2  Canned Soda        [Diet Coke]        2.18
3866      1550         2  Canned Soda     [Mountain Dew]        2.18

In [31]:
len(chipo_ml)

20

In [32]:
print ("Number of times Veggie Salad Bowl is ordered")

# It can be any item 
chipo_salad = location[location.item_name == 'Veggie Salad Bowl']
len(chipo_salad)

Number of times Veggie Salad Bowl is ordered

18

### Grouping in EDA

- Allow characteristics of the data to be more easily interpreted than would be true if the raw data were to be examined. 
- Improves the accuracy/efficiency estimation
- Permits greater balancing statistical power of tests of difference between strata by sampling equal numbers from strata 

Notes: Strata refers to sampling method in which total population is divided into non-overlapping subgroups

In [33]:
# NaN in group by are automatically excluded,
# not explicitly droping NaN values 

item_nm = location.groupby('item_name')

In [34]:
# To understand the total quantity ordered across each item 
# Also, the total cost for that item we use below function 

dfn = item_nm.sum()
dfn

                                       order_id  quantity  item_price
item_name
6 Pack Soft Drink                         52322        55      356.95
Barbacoa Bowl                             53972        66      672.36
Barbacoa Burrito                          74718        91      894.75
Barbacoa Crispy Tacos                      5613        12      120.21
Barbacoa Salad Bowl                        9708        10      106.40
Barbacoa Soft Tacos                       18725        25      250.46
Bottled Water                            175944       211      302.56
Bowl                                        472         4       29.60
Burrito                                    1550         6       44.40
Canned Soda                               76396       126      137.34
Canned Soft Drink                        304753       351      438.75
Carnitas Bowl                             62742        71      736.71
Carnitas Burrito                          51652        60      597.83
Carnitas Crispy Tacos                      5868         8       77.96
Carnitas Salad                             1500         1        8.99
Carnitas Salad Bowl                        6693         6       66.34
Carnitas Soft Tacos                       37673        40      375.94
Chicken Bowl                             713926       761     7342.73
Chicken Burrito                          497303       591     5575.82
Chicken Crispy Tacos                      47382        50      472.13
Chicken Salad                             10465         9       81.09
Chicken Salad Bowl                       117104       123     1228.75
Chicken Soft Tacos                        98395       120     1108.09
Chips                                    208004       230      494.34
Chips and Fresh Tomato Salsa             100419       130      361.36
Chips and Guacamole                      449959       506     2201.04
Chips and Mild Fresh Tomato Salsa           279         1        3.00
Chips and Roasted Chili Corn Salsa        14999        23       67.85
Chips and Roasted Chili-Corn Salsa        17462        18       43.02
Chips and Tomatillo Green Chili Salsa     41170        45      132.75
Chips and Tomatillo Red Chili Salsa       45556        50      147.50
Chips and Tomatillo-Green Chili Salsa     21826        33       78.87
Chips and Tomatillo-Red Chili Salsa       18344        25       59.75
Crispy Tacos                                434         2       14.80
Izze                                      10587        20       67.80
Nantucket Nectar                          21814        29       98.31
Salad                                      1150         2       14.80
Side of Chips                             84769       110      185.90
Steak Bowl                               193752       221     2260.19
Steak Burrito                            328437       386     3851.43
Steak Crispy Tacos                        35818        36      357.34
Steak Salad                                2362         4       35.66
Steak Salad Bowl                          29590        31      343.59
Steak Soft Tacos                          50177        56      536.05
Veggie Bowl                               72270        87      867.99
Veggie Burrito                            80962        97      934.77
Veggie Crispy Tacos                         668         1        8.49
Veggie Salad                               7265         6       50.94
Veggie Salad Bowl                         17303        18      182.50
Veggie Soft Tacos                          5520         8       73.96

In [35]:
# Sort the above list based on quantity
# To know the highest/lowest preferred item along with its price  
sort_list = dfn.sort_values(['quantity'],ascending = False)
sort_list.head(1)

              order_id  quantity  item_price
item_name
Chicken Bowl    713926       761     7342.73

In [36]:
print ('Most ordered item : ' + str(location.item_name.value_counts().head()))

Most ordered item : Chicken Bowl           726
Chicken Burrito        553
Chips and Guacamole    479
Steak Burrito          368
Canned Soft Drink      301
Name: item_name, dtype: int64

In [37]:
print('Count of Most ordered item : ' + str(location.item_name.value_counts().max()))

Count of Most ordered item : 726

In [38]:
cnt = location['item_name'].unique()
count = len(cnt)
print('Count of items ordered: ' + str(count))

Count of items ordered: 50

In [41]:
# Group by choice_description 
# To draw some conclusion about customer preference 

# Get rid of NaNs 
# NaN in group by are automatically excluded. 
# This step can be excluded 

df = location.dropna(how='any')
print('After dropping NaNs : ')
df

After dropping NaNs :

,order_id,quantity,item_name,choice_description,item_price
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
18,9,2,Canned Soda,[Sprite],2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
24,12,1,Izze,[Grapefruit],3.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.99
28,14,1,Canned Soda,[Dr. Pepper],1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
31,16,1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",8.99
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.99
35,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, Rice]",8.75
36,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
43,20,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",11.75
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75
...,...,...,...,...,...
4583,1823,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
4585,1823,1,Canned Soft Drink,[Diet Coke],1.25
4586,1824,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
4587,1824,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
4589,1825,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.25
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",8.75
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",11.75
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
4597,1826,1,Canned Soft Drink,[Nestea],1.25
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75
4601,1827,1,Canned Soft Drink,[Diet Coke],1.25
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
4606,1828,1,Canned Soft Drink,[Coke],1.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4609,1829,1,Canned Soft Drink,[Sprite],1.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",8.75
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [48]:
# Group Data by choice_description 
ch_des = df.groupby('choice_description')

# Do summation across groups. 
# Again to know the most preferred choice and cost 
dfn1 = ch_des.sum()
print('\nAfter grouping Data across choice_description :')
dfn1

After grouping Data across choice_description :

,order_id,quantity,item_price
choice_description,,,
"[Adobo-Marinated and Grilled Chicken, Pinto Beans, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",214,1,7.40
"[Adobo-Marinated and Grilled Chicken, [Sour Cream, Cheese, Cilantro-Lime Rice]]",279,1,7.40
[Adobo-Marinated and Grilled Chicken],217,1,7.40
"[Adobo-Marinated and Grilled Steak, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",279,1,7.40
[Adobo-Marinated and Grilled Steak],217,1,7.40
[Apple],3966,6,20.34
[Blackberry],5220,8,27.12
"[Braised Barbacoa, Pinto Beans, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",217,1,7.40
"[Braised Barbacoa, Vegetarian Black Beans, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice]]",214,1,7.40
"[Braised Carnitas, Pinto Beans, [Sour Cream, Cheese, Cilantro-Lime Rice]]",193,3,22.20
"[Brown Rice, Adobo-Marinated and Grilled Chicken, Vegetarian Black Beans]",575,1,7.40
[Brown Rice],1793,1,8.99
[Clementine],4777,8,27.12
[Coca Cola],19282,32,34.88
[Coke],122752,143,288.79
[Diet Coke],123455,159,326.71
[Diet Dr. Pepper],10405,14,15.26
[Dr. Pepper],13223,21,22.89
"[Fresh Tomato (Mild), [Black Beans, Guacamole, Rice, Sour Cream, Cheese]]",1252,1,11.08
"[Fresh Tomato (Mild), [Black Beans, Rice, Sour Cream, Cheese]]",3128,2,16.88
"[Fresh Tomato (Mild), [Guacamole, Lettuce, Pinto Beans, Rice, Sour Cream, Cheese]]",868,2,22.16
"[Fresh Tomato (Mild), [Guacamole, Lettuce, Rice, Fajita Veggies, Cheese]]",453,1,10.58
"[Fresh Tomato (Mild), [Guacamole, Lettuce, Rice, Fajita Veggies, Sour Cream, Cheese]]",204,1,10.58
"[Fresh Tomato (Mild), [Guacamole, Lettuce, Rice, Sour Cream, Cheese]]",527,1,11.08
"[Fresh Tomato (Mild), [Guacamole, Rice, Black Beans]]",666,1,11.08
"[Fresh Tomato (Mild), [Guacamole, Rice, Fajita Veggies, Sour Cream, Cheese]]",479,1,10.58
"[Fresh Tomato (Mild), [Guacamole, Rice, Sour Cream, Cheese]]",1415,1,10.58
"[Fresh Tomato (Mild), [Guacamole, Rice]]",1160,1,10.58
"[Fresh Tomato (Mild), [Guacamole, Sour Cream, Cheese]]",1041,2,22.16
"[Fresh Tomato (Mild), [Lettuce, Black Beans, Guacamole, Rice, Sour Cream, Cheese]]",1146,1,11.08
...,...,...,...
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Black Beans, Rice, Fajita Veggies, Lettuce]]",8150,6,50.94
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Pinto Beans, Rice, Fajita Veggies, Cheese, Sour Cream, Guacamole, Lettuce]]",538,1,10.98
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Pinto Beans, Rice, Fajita Veggies, Cheese, Sour Cream, Lettuce]]",1607,2,17.48
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Black Beans, Rice, Cheese, Guacamole]]",202,1,11.48
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Black Beans, Rice, Cheese, Sour Cream, Lettuce]]",439,1,8.49
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Black Beans, Rice, Cheese]]",424,1,8.49
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Black Beans, Rice, Fajita Veggies, Cheese, Sour Cream, Guacamole]]",1025,1,10.98
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Black Beans, Rice, Fajita Veggies, Cheese, Sour Cream, Lettuce]]",1284,2,17.48
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Black Beans, Rice, Sour Cream, Lettuce]]",14,1,8.99
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Pinto Beans, Black Beans, Rice, Fajita Veggies, Cheese, Sour Cream, Guacamole, Lettuce]]",871,1,10.98
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Rice, Cheese, Sour Cream, Guacamole, Lettuce]]",992,2,22.46
"[[Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Rice, Fajita Veggies, Guacamole, Lettuce]]",2129,2,22.46
"[[Tomatillo-Green Chili Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Black Beans, Rice, Cheese, Lettuce]]",667,1,8.99
"[[Tomatillo-Green Chili Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Black Beans, Rice, Cheese, Sour Cream, Guacamole]]",435,1,10.98
"[[Tomatillo-Green Chili Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Black Beans, Rice, Fajita Veggies, Sour Cream]]",513,2,17.98
"[[Tomatillo-Green Chili Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Pinto Beans, Rice, Cheese, Sour Cream, Guacamole, Lettuce]]",12,1,10.98
"[[Tomatillo-Green Chili Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Pinto Beans, Rice, Fajita Veggies, Cheese, Sour Cream, Guacamole]]",1470,1,10.98
"[[Tomatillo-Green Chili Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Rice, Cheese, Sour Cream, Lettuce]]",1002,1,8.99
"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato Salsa (Mild), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Cheese]]",108,1,8.99
"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato Salsa (Mild)], [Pinto Beans, Cheese, Guacamole, Lettuce]]",988,1,11.48
"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato Salsa (Mild)], [Rice, Black Beans, Cheese, Lettuce]]",76,1,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato Salsa (Mild)], [Rice, Black Beans, Lettuce]]",1338,1,8.99
"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato Salsa (Mild)], [Rice, Fajita Veggies, Cheese, Sour Cream, Guacamole, Lettuce]]",579,1,11.48
"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato Salsa (Mild)], [Rice, Pinto Beans, Cheese, Guacamole]]",1010,1,11.48
"[[Tomatillo-Red Chili Salsa (Hot), Roasted Chili Corn Salsa (Medium)], [Guacamole, Cheese, Sour Cream]]",186,1,10.98
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Black Beans, Cheese, Lettuce]]",2576,2,16.98
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Black Beans, Lettuce]]",1215,1,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Cheese, Lettuce]]",51,1,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Fajita Veggies, Cheese, Sour Cream, Lettuce]]",51,1,8.99
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Fajita Veggies, Lettuce]]",1299,1,8.99

In [52]:
# Sort data based on the quantity ordered to display top 'N' and bottom 'N' records 
sort_list_cd = dfn1.sort_values(['quantity'],ascending=False)
print('\n Top 5 items after sorting the grouped Data by quantity :')
sort_list_cd.head()

 Top 5 items after sorting the grouped Data by quantity :

,order_id,quantity,item_price
choice_description,,,
[Diet Coke],123455,159,326.71
[Coke],122752,143,288.79
[Sprite],80426,89,133.93
"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Lettuce]]",43088,49,432.25
"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream]]",36041,42,372.64

In [53]:
print(' \n Last 5 items after sorting the grouped Data by quantity :')
sort_list_cd.tail()

 Last 5 items after sorting the grouped Data by quantity :

,order_id,quantity,item_price
choice_description,,,
"[Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Pinto Beans, Guacamole, Lettuce]]",577,1,11.25
"[Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Sour Cream, Lettuce]]",585,1,8.75
"[Roasted Chili Corn Salsa, [Fajita Vegetables, Sour Cream, Lettuce, Guacamole]]",235,1,11.75
"[Roasted Chili Corn Salsa, [Guacamole, Sour Cream, Rice, Fajita Vegetables, Lettuce]]",987,1,11.25
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Fajita Veggies, Lettuce]]",1299,1,8.99

In [55]:
sort_list_cd = dfn1.sort_values(['item_price'],ascending=False)
print('\n Top 5 items after sorting the grouped Data by item price :')
sort_list_cd.head()

 Top 5 items after sorting the grouped Data by item price :

,order_id,quantity,item_price
choice_description,,,
"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]",37550,40,455.50
"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Lettuce]]",43088,49,432.25
"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream]]",36041,42,372.64
[Diet Coke],123455,159,326.71
"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice, Cheese, Sour Cream]]",24432,36,311.64

In [56]:
sort_list_cd = dfn1.sort_values(['item_price'],ascending=False)
print('\n Top 5 items after sorting the grouped Data by item price :')
sort_list_cd.tail()

 Top 5 items after sorting the grouped Data by item price :

,order_id,quantity,item_price
choice_description,,,
"[Braised Barbacoa, Pinto Beans, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",217,1,7.4
[Adobo-Marinated and Grilled Steak],217,1,7.4
"[Adobo-Marinated and Grilled Steak, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",279,1,7.4
[Adobo-Marinated and Grilled Chicken],217,1,7.4
"[Adobo-Marinated and Grilled Chicken, Pinto Beans, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",214,1,7.4

In [60]:
# Group by 2 columns would help us to know most preferred combination
item_combined = location.groupby(['item_name','choice_description']).sum()
item_choice = item_combined.dropna(how='any')

# Sort the grouped data based on item_price 
sort_list_ic = item_choice.sort_values(['item_price'],ascending = False)
print(' \n Top 10 items after sorting the grouped data by item_price : ')
sort_list_ic.head(10)

 Top 10 items after sorting the grouped data by item_price :

                                                                      order_id  \
item_name         choice_description
Chicken Burrito   [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...     17682
                  [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...     13781
6 Pack Soft Drink [Diet Coke]                                            24539
Chicken Bowl      [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...     15003
Canned Soft Drink [Coke]                                                103312
Chicken Bowl      [Fresh Tomato Salsa, [Fajita Vegetables, Rice]]        14095
Canned Soft Drink [Diet Coke]                                            88465
Chicken Bowl      [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...     10990
6 Pack Soft Drink [Coke]                                                 19440
Chicken Burrito   [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...      8226

                                                                      quantity  \
item_name         choice_description
Chicken Burrito   [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...        21
                  [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...        19
6 Pack Soft Drink [Diet Coke]                                               25
Chicken Bowl      [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...        14
Canned Soft Drink [Coke]                                                   122
Chicken Bowl      [Fresh Tomato Salsa, [Fajita Vegetables, Rice]]           17
Canned Soft Drink [Diet Coke]                                              115
Chicken Bowl      [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...        16
6 Pack Soft Drink [Coke]                                                    21
Chicken Burrito   [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...        12

                                                                      item_price
item_name         choice_description
Chicken Burrito   [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...      183.75
                  [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...      166.25
6 Pack Soft Drink [Diet Coke]                                             162.25
Chicken Bowl      [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...      157.50
Canned Soft Drink [Coke]                                                  152.50
Chicken Bowl      [Fresh Tomato Salsa, [Fajita Vegetables, Rice]]         148.75
Canned Soft Drink [Diet Coke]                                             143.75
Chicken Bowl      [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...      140.00
6 Pack Soft Drink [Coke]                                                  136.29
Chicken Burrito   [Fresh Tomato Salsa, [Rice, Black Beans, Cheese...      135.00

In [61]:
print('\n Last 10 items after sorting the grouped data by item_price :')
sort_list_ic.tail(10)

 Last 10 items after sorting the grouped data by item_price :

                                                                 order_id  \
item_name    choice_description
Salad        [Brown Rice, Adobo-Marinated and Grilled Chicke...       575
             [White Rice, Adobo-Marinated and Grilled Chicke...       575
Burrito      [Adobo-Marinated and Grilled Chicken, [Sour Cre...       279
             [Braised Barbacoa, Pinto Beans, [Sour Cream, Sa...       217
             [Braised Barbacoa, Vegetarian Black Beans, [Sou...       214
             [White Rice, Adobo-Marinated and Grilled Steak,...       313
Crispy Tacos [Adobo-Marinated and Grilled Steak]                      217
Burrito      [White Rice, Adobo-Marinated and Grilled Steak,...       313
Crispy Tacos [Adobo-Marinated and Grilled Chicken]                    217
Burrito      [Adobo-Marinated and Grilled Chicken, Pinto Bea...       214

                                                                 quantity  \
item_name    choice_description
Salad        [Brown Rice, Adobo-Marinated and Grilled Chicke...         1
             [White Rice, Adobo-Marinated and Grilled Chicke...         1
Burrito      [Adobo-Marinated and Grilled Chicken, [Sour Cre...         1
             [Braised Barbacoa, Pinto Beans, [Sour Cream, Sa...         1
             [Braised Barbacoa, Vegetarian Black Beans, [Sou...         1
             [White Rice, Adobo-Marinated and Grilled Steak,...         1
Crispy Tacos [Adobo-Marinated and Grilled Steak]                        1
Burrito      [White Rice, Adobo-Marinated and Grilled Steak,...         1
Crispy Tacos [Adobo-Marinated and Grilled Chicken]                      1
Burrito      [Adobo-Marinated and Grilled Chicken, Pinto Bea...         1

                                                                 item_price
item_name    choice_description
Salad        [Brown Rice, Adobo-Marinated and Grilled Chicke...         7.4
             [White Rice, Adobo-Marinated and Grilled Chicke...         7.4
Burrito      [Adobo-Marinated and Grilled Chicken, [Sour Cre...         7.4
             [Braised Barbacoa, Pinto Beans, [Sour Cream, Sa...         7.4
             [Braised Barbacoa, Vegetarian Black Beans, [Sou...         7.4
             [White Rice, Adobo-Marinated and Grilled Steak,...         7.4
Crispy Tacos [Adobo-Marinated and Grilled Steak]                        7.4
Burrito      [White Rice, Adobo-Marinated and Grilled Steak,...         7.4
Crispy Tacos [Adobo-Marinated and Grilled Chicken]                      7.4
Burrito      [Adobo-Marinated and Grilled Chicken, Pinto Bea...         7.4